name: build_flash

on:
  workflow_dispatch:
  push: 
    branches: [OpenELA-4.14.y-Stock]

jobs:
  build-and-copy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Toolchains
        run: |
          # Install required tools and dependencies
          sudo apt-get update -y
          sudo apt-get install -y build-essential git cmake ninja-build

          # Download and install toolchains (adjust paths as needed)
          mkdir ~/toolchains
          cd ~/toolchains
          git clone https://gitlab.com/XSans0/weebx-clang.git

      - name: Build and Copy
        run: |
          cd ~/android_kernel_lge_sm8150
          bash build_flash.sh
